# Do not edit. Generated by the configure script.
export PATH:=/home/rafael/SerenityOS/serenity/Ports/nodejs/node-v14.16.0/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.8
PREFIX=/usr/local
